Vagrant.configure("2") do |config|
  config.vm.hostname = "tset-machine"
  config.vm.box = "Berkshelf-CentOS-6.3-x86_64-minimal"
  config.vm.box_url = "https://dl.dropbox.com/u/31081437/Berkshelf-CentOS-6.3-x86_64-minimal.box"
  config.vm.network "public_network", :bridge => 'en1: Wi-Fi (AirPort)'
  config.ssh.max_tries = 40
  config.ssh.timeout   = 120
  config.berkshelf.enabled = true
  config.chef_zero.enabled = true
  config.vm.provision :chef_client do |chef|
    chef.run_list = [
        "recipe[nginx::default]"
    ]
  end
end
